# General setup
anchor_1: &node_10
  docker:
    - image: circleci/node:10.16

anchor_2: &node_12
  docker:
    - image: circleci/node:12.4

anchor_3: &environment
  environment:
    BASH_ENV: ~/.profile
    NPM_CONFIG_PREFIX: ~/.npm-global

anchor_4: &setup
  run:
    name: Setup environment
    command: ./global-setup.sh

# Projects

# From https://github.com/johannesjo/super-productivity
anchor_11: &super_productivity
  <<: *environment
  steps:
    - checkout
    - *setup
    - run: 
        command: ./benchmark-project.sh https://github.com/alan-agius4/super-productivity/tree/v9-testing 46a6d70 yarn "node --max_old_space_size=2400 ./node_modules/@angular/cli/bin/ng build --prod"
        no_output_timeout: 90m

# From https://github.com/kubernetes/dashboard
anchor_12: &kubernetes_dashboard
  <<: *environment
  steps:
    - checkout
    - *setup
    - run: 
        command: ./benchmark-project.sh https://github.com/alan-agius4/dashboard/tree/v9-testing d1e4331 npm
        no_output_timeout: 90m

# From https://github.com/angular/angular/tree/master/aio
anchor_13: &aio
  <<: *environment
  steps:
    - checkout
    - *setup
    - run: 
        command: ./benchmark-project.sh https://github.com/alan-agius4/angular/tree/v9-testing b80dc43 yarn "ng build --configuration=stable" aio
        no_output_timeout: 90m

version: 2
jobs:
  noop:
    <<: *node_10
    steps:
      - run: echo dummy job, just here so circleci is green when no other job is running.

  super_productivity-node_10:
    <<: *node_10
    <<: *super_productivity

  super_productivity-node_12:
    <<: *node_12
    <<: *super_productivity

  kubernetes_dashboard-node_10:
    <<: *node_10
    <<: *kubernetes_dashboard

  kubernetes_dashboard-node_12:
    <<: *node_12
    <<: *kubernetes_dashboard

  aio-node_10:
    <<: *node_10
    <<: *aio

  aio-node_12:
    <<: *node_12
    <<: *aio

workflows:
  version: 2
  default_workflow:
    jobs:
      # - noop
      - super_productivity-node_10
      - super_productivity-node_12
      - kubernetes_dashboard-node_10
      - kubernetes_dashboard-node_12
      - aio-node_10
      - aio-node_12
