# General setup
anchor_1: &node_10
  docker:
    - image: circleci/node:10.16

anchor_2: &node_12
  docker:
    - image: circleci/node:12.10

anchor_3: &environment
  environment:
    BASH_ENV: ~/.profile
    NPM_CONFIG_PREFIX: ~/.npm-global

anchor_4: &setup
  run:
    name: Setup environment
    command: ./global-setup.sh

# Projects

# From https://github.com/angular/angular/tree/master/aio
anchor_13_s: &aio
  <<: *environment
  steps:
    - checkout
    - *setup
    - run: 
        command: ./benchmark-project.sh https://github.com/alan-agius4/angular v9-testing yarn "ng build --configuration=fast --aot --source-map --watch --progress" aio
        no_output_timeout: 90m

version: 2
jobs:
  aio:
    <<: *node_12
    <<: *aio

workflows:
  version: 2
  default_workflow:
    jobs:
      - aio