# General setup
anchor_1: &node_10
  docker:
    - image: circleci/node:10

anchor_2: &node_12
  docker:
    - image: circleci/node:12

anchor_3: &environment
  environment:
    BASH_ENV: ~/.profile
    NPM_CONFIG_PREFIX: ~/.npm-global

anchor_4: &setup
  run:
    name: Setup environment
    command: ./global-setup.sh

# Projects

# New project created by `ng new`
anchor_10: &new_project
  <<: *environment
  steps:
    - checkout
    - *setup
    - run: 
        command: ./benchmark-project.sh https://github.com/filipesilva/cli-eight-project 02cfbec npm
        no_output_timeout: 90m

# From https://github.com/johannesjo/super-productivity    
anchor_11: &super_productivity
  <<: *environment
  steps:
    - checkout
    - *setup
    - run: 
        command: ./benchmark-project.sh https://github.com/filipesilva/super-productivity e6501816 yarn
        no_output_timeout: 90m

# From https://github.com/johnpapa/awesome-angular-workshop/tree/v8
anchor_12: &awesome_angular_workshop
  <<: *environment
  steps:
    - checkout
    - *setup
    - run: 
        command: ./benchmark-project.sh https://github.com/johnpapa/awesome-angular-workshop b7adca7 npm "ng build 5-ngrx-end --prod"
        no_output_timeout: 90m

# From https://github.com/angular/angular/tree/master/aio
anchor_13: &aio
  <<: *environment
  steps:
    - checkout
    - *setup
    - run: 
        command: ./benchmark-project.sh https://github.com/filipesilva/angular c6d7b7ebc yarn "ng build --configuration=stable" aio
        no_output_timeout: 90m

version: 2
jobs:
  noop:
    <<: *node_10
    steps:
      - run: echo dummy job, just here so circleci is green when no other job is running.

  new_project-node_10:
    <<: *node_10
    <<: *new_project

  new_project-node_12:
    <<: *node_12
    <<: *new_project

  super_productivity-node_10:
    <<: *node_10
    <<: *super_productivity

  super_productivity-node_12:
    <<: *node_12
    <<: *super_productivity

  awesome_angular_workshop-node_10:
    <<: *node_10
    <<: *awesome_angular_workshop

  awesome_angular_workshop-node_12:
    <<: *node_12
    <<: *awesome_angular_workshop

  aio-node_10:
    <<: *node_10
    <<: *aio

  aio-node_12:
    <<: *node_12
    <<: *aio

workflows:
  version: 2
  default_workflow:
    jobs:
      - noop
      # - new_project-node_10
      # - new_project-node_12
      # - super_productivity-node_10
      # - super_productivity-node_12
      # - awesome_angular_workshop-node_10
      # - awesome_angular_workshop-node_12
      # - aio-node_10
      # - aio-node_12